name = "tame-del-pezzo"
version = "0.1.0"
defaultTargets = ["TameDelPezzo", "certificate"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "520045ab14e26149ee970e2e617ca04b09bde5d6"

[[lean_lib]]
name = "TameDelPezzo"

[[lean_exe]]
name = "certificate"
root = "Main"
